## Data Storytelling using titanic dataset Exploratory data analysis

In [15]:
# What is EDA (Exploratory Data Analysis)
# Steps to follow for EDA:
# Understanding the data
# Cleaning the data
# Feature selections: this helps identity which variables are most important for your problem (feature engineering & selection)
# Assumtions checking: this allows you to check assumpttions that are required for certain machine learning models
# Generally dataset have two types of columns categorical column and numerical columnn. can there can be more than this type of columns?

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style='whitegrid')

##### Data loading and initial inspection of data

In [7]:
!git clone "https://github.com/Py-Ninad/Datasets"

Cloning into 'Datasets'...
Updating files:  21% (53/245)
Updating files:  22% (54/245)
Updating files:  23% (57/245)
Updating files:  24% (59/245)
Updating files:  25% (62/245)
Updating files:  26% (64/245)
Updating files:  27% (67/245)
Updating files:  28% (69/245)
Updating files:  29% (72/245)
Updating files:  30% (74/245)
Updating files:  31% (76/245)
Updating files:  32% (79/245)
Updating files:  33% (81/245)
Updating files:  34% (84/245)
Updating files:  35% (86/245)
Updating files:  36% (89/245)
Updating files:  37% (91/245)
Updating files:  38% (94/245)
Updating files:  39% (96/245)
Updating files:  40% (98/245)
Updating files:  41% (101/245)
Updating files:  42% (103/245)
Updating files:  43% (106/245)
Updating files:  44% (108/245)
Updating files:  45% (111/245)
Updating files:  46% (113/245)
Updating files:  47% (116/245)
Updating files:  48% (118/245)
Updating files:  49% (121/245)
Updating files:  50% (123/245)
Updating files:  51% (125/245)
Updating files:  52% (128/245)
Updating files:  53% (130/245)
Updating files:  54% (133/245)
Updating files:  55% (135/245)
Updating files:  56% (138/245)
Updating files:  57% (140/245)
Updating files:  58% (143/245)
Updating files:  59% (145/245)
Updating files:  60% (147/245)
Updating files:  61% (150/245)
Updating files:  62% (152/245)
Updating files:  63% (155/245)
Updating files:  64% (157/245)
Updating files:  65% (160/245)
Updating files:  66% (162/245)
Updating files:  67% (165/245)
Updating files:  68% (167/245)
Updating files:  69% (170/245)
Updating files:  70% (172/245)
Updating files:  71% (174/245)
Updating files:  72% (177/245)
Updating files:  73% (179/245)
Updating files:  74% (182/245)
Updating files:  75% (184/245)
Updating files:  76% (187/245)
Updating files:  77% (189/245)
Updating files:  78% (192/245)
Updating files:  79% (194/245)
Updating files:  80% (196/245)
Updating files:  81% (199/245)
Updating files:  82% (201/245)
Updating files:  83% (204/245)
Updating files:  84% (206/245)
Updating files:  85% (209/245)
Updating files:  86% (211/245)
Updating files:  87% (214/245)
Updating files:  88% (216/245)
Updating files:  88% (218/245)
Updating files:  89% (219/245)
Updating files:  90% (221/245)
Updating files:  91% (223/245)
Updating files:  92% (226/245)
Updating files:  93% (228/245)
Updating files:  94% (231/245)
Updating files:  95% (233/245)
Updating files:  96% (236/245)
Updating files:  97% (238/245)
Updating files:  98% (241/245)
Updating files:  99% (243/245)
Updating files: 100% (245/245)
Updating files: 100% (245/245), done.

In [8]:
df = pd.read_csv("Datasets/Titanic_Dataset/Titanic-Dataset.csv")

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [12]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [14]:
df.tail(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [16]:
print('Dataset information')
df.info()

Dataset information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [17]:
# Insights:
# This dataset have both null values as well as non-null values.
# we need to check null values quantity if any of column have more null values then need to focus on that columns
# so cleaning and sorting of dataset will be simple

In [18]:
print('Describe Dataset')
df.describe()

Describe Dataset

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200